[project]
name = "day11-managed-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.24.1",
    "google-genai>=1.62.0",
]
